apiVersion: v1
kind: Service
metadata:
  name: nx-app-service
spec:
  selector:
    app: nx-app
  ports:
    - protocol: TCP
      port: 80         # Port that users will access
      targetPort: 5000  # Port inside the container
  type: LoadBalancer   # If you need external access, or use NodePort

